### ISSUE TITLE
How include this project to Synapse?

### ISSUE THREAD

**Issue by ahvahsky2008** [tulir/mautrix-whatsapp#140]
Tell me the minimum settings to make this connector work? Manuall in Readme is is very superficial

**Comment by tulir** [comment]
Did you read the wiki (that's linked in the readme)?

**Comment by ahvahsky2008** [comment]
> Did you read the wiki (that's linked in the readme)?

Yes I do.

**Comment by ahvahsky2008** [comment]
1) You need to make sure that the address and domain field point to your homeserver.
![image](https://user-images.githubusercontent.com/8035828/73063312-93515000-3eaf-11ea-8878-35ce410d79ec.png)
2) You will also need to add your user of admin user under the permissions section.
![image](https://user-images.githubusercontent.com/8035828/73063344-a3692f80-3eaf-11ea-88b9-defffad321b5.png)
3) Generate the appservice registration file by running ./mautrix-whatsapp -g.
![image](https://user-images.githubusercontent.com/8035828/73063404-c3005800-3eaf-11ea-950b-0799e86d0a23.png)
4) Add the path to the registration file (registration.yaml by default) to your synapse homeserver.yaml under app_service_config_files. You will then need to restart the synapse server. Remember to restart it every time the registration file is regenerated.
![image](https://user-images.githubusercontent.com/8035828/73063453-ddd2cc80-3eaf-11ea-8328-7a0f81aa1342.png)
5) Run the bridge with ./mautrix-whatsapp.
![image](https://user-images.githubusercontent.com/8035828/73063479-e925f800-3eaf-11ea-952c-ead82d6ecf6d.png)

**Comment by vmario89** [comment]
Hi,
http 502  means "Bad Gateway". Maybe your apache/httpd/nginx/whatever web server is not configured correctly. 

What happens when you access your homeserver url at this point in browser or by curl?

you can try our's for reference: https://matrix.fablabchemnitz.de/_matrix/client/r0/Account/whoami
![grafik](https://user-images.githubusercontent.com/5631071/73064295-32228000-3ea1-11ea-8075-262a02d4eaa8.png)

**Comment by ahvahsky2008** [comment]
![image](https://user-images.githubusercontent.com/8035828/73064849-2fc92180-3eb3-11ea-80ea-23764107e28b.png)

**Comment by ahvahsky2008** [comment]
![image](https://user-images.githubusercontent.com/8035828/73064905-4ec7b380-3eb3-11ea-877b-9e3ff8b5e652.png)

**Comment by vmario89** [comment]
hi,
yeah it should be that issue. i think your whatsapp thing is configured properly.
to make it work you need to make API available

you can use  https://github.com/kamax-matrix/mxisd/blob/master/docs/getting-started.md for reference

```
    ProxyPreserveHost on
 
    ProxyPass /_matrix/identity http://localhost:8090/_matrix/identity
    ProxyPass /_matrix http://localhost:8008/_matrix
```
 

hopefully thats the thing which fixed your issue

**Comment by ahvahsky2008** [comment]
![image](https://user-images.githubusercontent.com/8035828/73066649-a536f100-3eb7-11ea-884e-adee33ef1aef.png)

I dont have services on this ports

**Comment by vmario89** [comment]
at least 8008 should be listening if you configured matrix with standard ports:

```
pid_file: "/var/run/matrix-synapse.pid"
public_baseurl: https://matrix.yourdomain.de/
soft_file_limit: 0
use_presence: true
listeners:
   - port: 8448
     type: http
     bind_addresses:
       - '0.0.0.0'
     tls: true
     x_forwarded: false
     resources:
       - names: [client, federation, consent]
  - port: 8008
    tls: false
    bind_addresses: ['::1', '127.0.0.1']
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation, consent]
        compress: false
```
