### ISSUE TITLE
Not able to see 1:1 rooms at first sync - pm error

### ISSUE THREAD

**Issue by floviolleau** [tulir/mautrix-whatsapp#236]
Hi,

Thanks for your amazing job for the ecosystem!
You made a good job of a complicated protocol.

I ran several commands without issues except the last one:
- !wa help
- !wa login
- !wa reconnect
- !wa list contacts
- !wa list groups
- !wa pm \<international phone number\>

But for the last one, I faced to an issue.
I have this error in the logs:

```
[...]
[Nov  7, 2020 02:22:22] [User/relaybot/INFO] Syncing portals
[Nov  7, 2020 02:22:22] [User/relaybot/INFO] Finished syncing portals
[Nov  7, 2020 02:22:24] [User/relaybot/DEBUG] Locking processing of incoming messages and starting post-login sync
[Nov  7, 2020 02:22:24] [User/relaybot/DEBUG] Chat list receive confirmation received in PostLogin
[Nov  7, 2020 02:22:25] [User/relaybot/DEBUG] Post-connection ping OK
[Nov  7, 2020 02:22:25] [User/relaybot/DEBUG] Post-login portal sync complete, unlocking processing of incoming messages.
[Nov  7, 2020 02:22:34] [Matrix/@whatsapp_<redacted>:domain.tld/DEBUG] POST https://domain.tld/_matrix/client/r0/register?user_id=%40whatsapp_<redacted>%3Adomain.tld {"username":"whatsapp_<redacted>","initial_device_display_name":""}
[Nov  7, 2020 02:22:34] [Matrix/@whatsapp_<redacted>:domain.tld/DEBUG] PUT https://domain.tld/_matrix/client/r0/profile/@whatsapp_<redacted>:domain.tld/displayname?user_id=%40whatsapp_<redacted>%3Adomain.tld {"displayname":"<redacted>(WA)"}
[Nov  7, 2020 02:22:42] [Command handler/DEBUG] @<redacted>:<redacted> sent 'pm <redacted>' in !<redacted>:domain.tld
[Nov  7, 2020 02:22:42] [Command handler/DEBUG] Importing <redacted>@s.whatsapp.net for &{0x246a0f0 0x2510b80 0x2216080 0x246a150 false false true true 0  false 0 1604712144 0x2227600 0x2227640 0x21a3a00 0x2227680 {{} [0 0 0]} {0 0}}
[Nov  7, 2020 02:22:42] [Matrix/@whatsapp_<redacted>:domain.tld/DEBUG] POST https://domain.tld/_matrix/client/r0/rooms/%21<redacted>:domain.tld/invite?user_id=%40whatsapp_<redacted>%3Adomain.tld {"user_id":"relaybot"}
[Nov  7, 2020 02:22:42] [Portal/<redacted>@s.whatsapp.net-<redacted>@s.whatsapp.net/WARN] Failed to invite relaybot to portal: failed to POST /_matrix/client/r0/rooms/!<redacted>:domain.tld/invite: M_INVALID_PARAM (HTTP 400): Expected UserID string to start with '@'. Creating new portal
[Nov  7, 2020 02:22:51] [User/relaybot/INFO] Finished syncing puppet info from contacts
```

<details>
  <summary>Click me to expand and see config!</summary>

```
homeserver:
  address: https://domain.tld
  domain: domain.tld
  asmux: false
appservice:
  address: http://localhost:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: sqlite3
    uri: mautrix-whatsapp.db
    max_open_conns: 20
    max_idle_conns: 2
  provisioning:
    prefix: /_matrix/provision/v1
    shared_secret: disable
  id: whatsapp
  bot:
    username: buddybot
    displayname: ""
    avatar: ""
  as_token: <redacted>
  hs_token: <redacted>
metrics:
  enabled: false
  listen: 127.0.0.1:8001
whatsapp:
  os_name: Matrix-WhatsApp bridge
  browser_name: mx-wa
bridge:
  username_template: whatsapp_{{.}}
  displayname_template: '{{if .Notify}}{{.Notify}}{{else}}{{.Jid}}{{end}} (WA)'
  community_template: whatsapp_{{.Localpart}}={{.Server}}
  connection_timeout: 120
  fetch_message_on_timeout: false
  delivery_receipts: false
  login_qr_regen_count: 2
  max_connection_attempts: 3
  connection_retry_delay: 30
  report_connection_retry: true
  chat_list_wait: 30
  portal_sync_wait: 600
  user_message_buffer: 1024
  portal_message_buffer: 128
  call_notices:
    start: true
    end: true
  initial_chat_sync_count: 10
  initial_history_fill_count: 20
  initial_history_disable_notifications: false
  recovery_chat_sync_count: -1
  recovery_history_backfill: true
  sync_max_chat_age: 259200
  sync_with_custom_puppets: true
  sync_direct_chat_list: false
  default_bridge_receipts: true
  default_bridge_presence: true
  login_shared_secret: ""
  invite_own_puppet_for_backfilling: true
  private_chat_portal_meta: false
  resend_bridge_info: false
  whatsapp_thumbnail: false
  allow_user_invite: true
  command_prefix: '!wa'
  encryption:
    allow: false
    default: false
    key_sharing:
      allow: false
      require_cross_signing: false
      require_verification: true
  permissions:
    '*': 5
    '@admin:domain.tld': 100
    domain.tld: 10
  relaybot:
    enabled: true
    management: '!<redacted>:domain.tld'
    invites: ['@admin:domain.tld']
    message_formats:
      m.audio: <b>{{ .Sender.Displayname }}</b> sent an audio file
      m.emote: '* <b>{{ .Sender.Displayname }}</b> {{ .Message }}'
      m.file: <b>{{ .Sender.Displayname }}</b> sent a file
      m.image: <b>{{ .Sender.Displayname }}</b> sent an image
      m.location: <b>{{ .Sender.Displayname }}</b> sent a location
      m.notice: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.text: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.video: <b>{{ .Sender.Displayname }}</b> sent a video
logging:
  directory: ./logs
  file_name_format: '{{.Date}}-{{.Index}}.log'
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: debug
```
</details>

I don't understand why the invited used in the relaybot config is not part of the post.

Any ideas?

Thanks!
