### ISSUE TITLE
Document PostgreSQL usage in the config?

### ISSUE THREAD

**Issue by IngwiePhoenix** [tulir/mautrix-whatsapp#239]
I would love to migrate from using sqlite to Postgres as my server still uses a HDD instead of an SSD because it's quite an old box. So I would love to use PostgreSQL to help this a little bit.

How would I do that? Thanks :)

**Comment by Nothing4You** [comment]
```
mautrix-whatsapp --help
mautrix-whatsapp - A Matrix-WhatsApp puppeting bridge.

Usage:
  mautrix-whatsapp [-h] [-c <path>] [-r <path>] [-g] [--migrate-db <source type> <source uri>]

Application options:
  -c, --config                    The path to your config file.
  -r, --registration              The path where to save the appservice registration.
  -g, --generate-registration     Generate registration and quit.
  -v, --version                   View bridge version and quit.
  --ignore-unsupported-database   Run even if database is too new
  --migrate-db                    Source database type and URI to migrate from.

Help options:
  -h, --help                      Show this help page.
```

**Comment by tobymurray** [comment]
I think a working example is captured in the config [here](https://github.com/tulir/mautrix-whatsapp/blob/464a7ee7653ee49ab818026dd738cee5b9856969/example-config.yaml#L19)

```
    # Database config.
    database:
        # The database type. "sqlite3" and "postgres" are supported.
        type: sqlite3
        # The database URI.
        #   SQLite: File name is enough. https://github.com/mattn/go-sqlite3#connection-string
        #   Postgres: Connection string. For example, postgres://user:password@host/database?sslmode=disable
        uri: mautrix-whatsapp.db
        # Maximum number of connections. Mostly relevant for Postgres.
        max_open_conns: 20
        max_idle_conns: 2
```
