### ISSUE TITLE
Appservice Worker don't work 

### ISSUE THREAD

**Issue by DoM1niC** [tulir/mautrix-whatsapp#250]
Appservice Worker don't work in my case 

```
worker_app: synapse.app.appservice

worker_replication_host: 127.0.0.1
worker_replication_port: 9009
worker_replication_http_port: 9008

worker_listeners:
    - type: http
      port: 8008
      tls: false
      bind_address: '127.0.0.1'
      tls: false
      resources:
        - names: 
          - client

worker_daemonize: false
send_federation: false
update_user_directory: false
start_pushers: false
notify_appservices: false
```

`Failed to connect to homeserver: failed to GET /_matrix/client/r0/account/whoami: M_UNRECOGNIZED (HTTP 400): Unrecognized request. Retrying in 10 seconds...
`
Other Bridges works so far like your Facebook / Signal Bridge react on help and so on ....
