### ISSUE TITLE
Invalid macaroon passed

### ISSUE THREAD

**Issue by FlorianJSa** [tulir/mautrix-whatsapp#253]
Hello I have set up the mautrix-whatsapp using docker. Unfortunately I get the following error see below, which I can't explain. I have adjusted the server address and the server address in the config.yaml also the settings in the registration.yaml are adjusted correctly.  

```[Jan 11, 2021 21:02:54] [ERROR] Failed to connect to homeserver: failed to GET /_matrix/client/r0/account/whoami: M_UNKNOWN_TOKEN (HTTP 401): Invalid macaroon passed.. Retrying in 10 seconds...```

The homeserver.yamle looks like this 

```
app_service_config_files:
      - data/registration.yaml
```

**Comment by sackett** [comment]
1. try full path like:
/etc/mautrix-whatsapp/data/registration.yaml
2. compare the tokens in registration.yaml and config.yaml

**Comment by FlorianJSa** [comment]
Thanks for your answer i will check that tomorrow

**Comment by FlorianJSa** [comment]
>     1. try full path like:
>        /etc/mautrix-whatsapp/data/registration.yaml
> 
>     2. compare the tokens in registration.yaml and config.yaml

Hello i have set the absolute Path, and checked the Tokens in config.yaml and in regisration.yaml same issue

**Comment by FlorianJSa** [comment]
I really have no idea what I am doing wrong

**Comment by Crisu1710** [comment]
Hi,
if you have a mount for your Synapse-Server copy your registration.yaml to this location.
like this
`
total 116
-rw-r--r--  1 991 991 91563 Jan  8 17:17 homeserver.yaml
-rw-r--r--  1 991 991   461 Jan  8 19:56 matrix.domain.tld.log.config
-rw-r--r--  1 991 991    59 Jan  5 21:23 matrix.domain.tld.signing.key
drwxr-xr-x  6 991 991  4096 Jan  8 20:12 media_store
-rw-------  1 991 991   429 Jan  8 20:32 registration.yaml
`
in homeserver.yaml use this

`
app_service_config_files:
  - /data/registration.yaml
#  - app_service_2.yaml
`

Make sure you replaced all example.domain  with your own in registration.yaml (the regex) and config.yaml
and in registration.yaml  set `url:` to your matrix container.

**Comment by FlorianJSa** [comment]
@Crisu1710 Thanks for your reply i am also from wuerzburg. Back to the topic the registration.yaml is in the data folder of synapse and all URLs have been changed. That is my config.yaml 

```ỳaml 



homeserver:
  address: XXX
  domain:XXXX
  asmux: false
appservice:
  address: http://localhost:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: sqlite3
    uri: mautrix-whatsapp.db
    max_open_conns: 20
    max_idle_conns: 2
  provisioning:
    prefix: /_matrix/provision/v1
    shared_secret: disable
  id: whatsapp
  bot:
    username: whatsappbot
    displayname: WhatsApp bridge bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
  as_token:XXXX
  hs_token: XXXXX
metrics:
  enabled: false
  listen: 127.0.0.1:8001
whatsapp:
  os_name: Mautrix-WhatsApp bridge
  browser_name: mx-wa
bridge:
  username_template: whatsapp_{{.}}
  displayname_template: '{{if .Notify}}{{.Notify}}{{else}}{{.Jid}}{{end}} (WA)'
  community_template: whatsapp_{{.Localpart}}={{.Server}}
  connection_timeout: 20
  fetch_message_on_timeout: false
  delivery_receipts: false
  login_qr_regen_count: 2
  max_connection_attempts: 3
  connection_retry_delay: -1
  report_connection_retry: true
  chat_list_wait: 30
  portal_sync_wait: 600
  user_message_buffer: 1024
  portal_message_buffer: 128
  call_notices:
    start: true
    end: true
  initial_chat_sync_count: 10
  initial_history_fill_count: 20
  initial_history_disable_notifications: false
  recovery_chat_sync_count: -1
  recovery_history_backfill: true
  sync_max_chat_age: 259200
  sync_with_custom_puppets: true
  sync_direct_chat_list: false
  default_bridge_receipts: true
  default_bridge_presence: true
  login_shared_secret: ""
  invite_own_puppet_for_backfilling: true
  private_chat_portal_meta: false
  resend_bridge_info: false
  whatsapp_thumbnail: false
  allow_user_invite: false
  command_prefix: '!wa'
  encryption:
    allow: false
    default: false
    key_sharing:
      allow: false
      require_cross_signing: false
      require_verification: true
  permissions:
    '*': 5
    '@xxxx:xxxx.xxxxx.de': 100
    xxx.xxx.de: 10
  relaybot:
    enabled: false
    management: '!foo:example.com'
    invites: []
    message_formats:
      m.audio: <b>{{ .Sender.Displayname }}</b> sent an audio file
      m.emote: '* <b>{{ .Sender.Displayname }}</b> {{ .Message }}'
      m.file: <b>{{ .Sender.Displayname }}</b> sent a file
      m.image: <b>{{ .Sender.Displayname }}</b> sent an image
      m.location: <b>{{ .Sender.Displayname }}</b> sent a location
      m.notice: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.text: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.video: <b>{{ .Sender.Displayname }}</b> sent a video
logging:
  directory: ./logs
  file_name_format: '{{.Date}}-{{.Index}}.log'
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: debug
```

**Comment by Crisu1710** [comment]
Hi @FlorianJSa, 
The config.yaml looks good, i made the a  mistake in the registration.yam, and got the same error message as you.
My registration.yam looks like this:

```
id: whatsapp
url: http://mautrix-whatsapp.matrix:29318  <- !! This URL should go to your mautrix-whatsapp container !!
as_token: P8ZgZQIhkOk62PsjimbYlpG8PCky1R3y9kWQCi1UV9PjhBXydzwNhVgh8IOBN3E5
hs_token: gKmoyWgJ0adkpJu0T4hXzHTjhy4pPVsj89CBZecertUY4oqGWZuDxaIiQ56F9m6W
sender_localpart: aGfrbt20gadPbnUHCe0vsE1PyVMeBQeG
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:matrix.domain.tld$  <- YOUR DOMAIN
    exclusive: true                                                            
  - regex: ^@whatsappbot:matrix.domain.tld$  <- YOUR DOMAIN
    exclusive: true
```
After I configured this it worked for me
