### ISSUE TITLE
Error while verifying cross-signing keys

### ISSUE THREAD

**Issue by Craeckie** [tulir/mautrix-whatsapp#264]
Whenever I create a direct e2ee chat with the whatsappbot, I get these errors:
`[Crypto/ERROR] Error while verifying cross-signing keys: the input base64 was invalid`

And in the client:
`⚠ Your message was not bridged: the bridge hasn't received the decryption keys. The bridge will retry for 10 seconds. If this error keeps happening, try restarting your client.`

Version: `mautrix-whatsapp 0.1.5+dev.95f64879 (Jan 25 2021, 19:02:14)`

Encryption config:
```
  encryption:
    allow: true
    default: false
    key_sharing:
      allow: true
      require_cross_signing: false
      require_verification: false
```

Is there some additional configuration required for e2ee to work?
