### ISSUE TITLE
Ability to set name or rename WhatsApp contact display name

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-whatsapp#86]
At now WhatsApp bridge bot don't provide any command to change display name for WhatsApp contact, so for contacts not in device addressbook I see names like `whatsapp_71234567890`.

And when WhatsApp application runs on virtual server, there are not too easy to open native app for add contact to address book and set name.

Will be good to implement function for set name or rename display name for WhatsApp contact via bridge. If renaming on WhatsApp side is not possible due to API restrictions, maybe implement rename on Matrix bridge side?

**Comment by dreamflasher** [comment]
Even with running whatsapp on a phone, the contact name is not synced. Bonus points for also syncing the contact photo.

**Comment by olmari** [comment]
Well... Syncing (names, profile, etc) hasn't had good track record on me either, but it's totally separate issue.

**Comment by renaudallard** [comment]
For group chats, this feature would really be helpful

**Comment by Ondolin** [comment]
Is there an update in this issue?

**Comment by AdriDevelopsThings** [comment]
Why does nobody of the developers comment to this issue, since 2 years?

**Comment by tulir** [comment]
Syncing names works just fine, so adding a way to set them manually is very low priority (probably won't happen unless someone contributes it).

**Comment by jswetzen** [comment]
What do I have to do to get contact names to sync? `sync contacts` just gave me numbers for everyone.

**Comment by marlos7** [comment]
I'm using this report, I recommend it!
https://github.com/jonalan7/Hydra-bot

**Comment by a22sc** [comment]
since using the whatsapp app is against the GDPR it would be great to rename certain contacts via mautrix-whatsapp directly. 
afaik it's possible to first change the powerlevel of your user in the room with `!wa set-pl matrix_userid 100` and then change the roomname. not sure if it persists a remote users namechange

**Comment by NewteqDeveloper** [comment]
You should already be able to do this, but I think there's a bug.
Because, from the configuration file you can see this
```yaml
brige:
    # Permissions for using the bridge.
    # Permitted values:
    #    relay - Talk through the relaybot (if enabled), no access otherwise
    # commands - Access to use commands in the bridge, but not login.
    #     user - Access to use the bridge with puppeting.
    #    admin - Full access, user level with some additional administration tools.
    # Permitted keys:
    #        * - All Matrix users
    #   domain - All users on that homeserver
    #     mxid - Specific user
    permissions:
        '*': relay
        'your.homeserver.com': user
        '@your-user:your.homeserver.com': admin
```

As @a22sc suggested though, doing the power-level command will sort out this problem. I don't know if it will persist with a user change on the remote server. But, if I find some time I'll look into this and see if it's a bug. Because there are config settings to address this. I don't know how long they've been there, but I do think the main issue has been addressed. We should create a new bug for what I've just mentioned
