### ISSUE TITLE
Errors on startup (Docker)

### ISSUE THREAD

**Issue by Zerwin** [tulir/mautrix-whatsapp#90]
Tried to use the latest Matrix Docker (so 1.3.2 I guess) and this bridge with Docker, but it fails on startup with following errors:

```
[Aug 24, 2019 15:13:51] [WARN] Failed to update bot avatar: msg=Failed to PUT JSON to /_matrix/client/r0/profile/@whatsappbot:xyz.com/avatar_url code=403 wrapped=M_FORBIDDEN: Application service cannot masquerade as this user.,
[Aug 24, 2019 15:13:51] [WARN] Failed to update bot displayname: msg=Failed to PUT JSON to /_matrix/client/r0/profile/@whatsappbot:xyz.com/displayname code=403 wrapped=M_FORBIDDEN: Application service cannot masquerade as this user.
```

In Riot it shows the user as offline. I fiddled around for some time but couldn't find a solution, and google also doesn't bring much up for me.

My registration.yaml (filtered with some stuff cause I don't know what is save to share)
```
id: whatsapp
url: http://localhost:29318
as_token: very-long-string-that-I-replaced
hs_token: very-long-string-that-I-replaced
sender_localpart: whatsappbot
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:xyz.com$
    exclusive: true
```
My app_service part from homeserver.yaml
```
# A list of application service config files to use
#
app_service_config_files:
  - "/data/mautrix-whatsapp/registration.yaml"
#  - app_service_1.yaml
#  - app_service_2.yaml
```

**Comment by tulir** [comment]
Is `appservice` -> `bot` -> `username` in the config same as `sender_localpart` in the registration?

**Comment by Zerwin** [comment]
```
bot:
    username: whatsappbot
    displayname: WhatsApp bridge bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
```
```
sender_localpart: whatsappbot
```

I am running them on the same machine, but apart from the bridge network they aren't in any other networks. To what should I set it ? The ip of the machine, or just put them both in a network and hope it resolves correctly ?
